### ISSUE TITLE
Error during helm bootstrap

### ISSUE THREAD

**Issue by zvfvrv** [ferrarimarco/kubernetes-playground#96] opened 2020-03-21 14:12 UTC
Following the steps in order to initialize Helm, i got the following error:

```shell
[vagrant@k8s-master-1 ~]$ sudo /vagrant/scripts/linux/bootstrap-helm.sh
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created
Creating /root/.helm 
Creating /root/.helm/repository 
Creating /root/.helm/repository/cache 
Creating /root/.helm/repository/local 
Creating /root/.helm/plugins 
Creating /root/.helm/starters 
Creating /root/.helm/cache/archive 
Creating /root/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Adding local repo with URL: http://127.0.0.1:8879/charts 
$HELM_HOME has been configured at /root/.helm.
Error: error installing: the server could not find the requested resource

the error occur during the execution of:
`/usr/local/bin/helm init --service-account tiller`
```

can find the output of the command `/usr/local/bin/helm init --service-account tiller --debug` attached  [here](https://github.com/ferrarimarco/kubernetes-playground/files/4362764/heml_init_dbug.txt)

the version of Helm is v2.8.2, but something odd occur also when i execute the command to retrieve the version of helm:

```shell
[vagrant@k8s-master-1 ~]$ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Error: cannot connect to Tiller
```

**Comment by ferrarimarco** [comment] 2020-03-21 18:47
apparently, you're using a different Helm version. I get a different error, because newer Helm version don't use Tiller anymore (and don't have an `init` command).

How did you install version `2.8.2`?

**Comment by ferrarimarco** [comment] 2020-03-21 18:50
By the way, I think this problem is caused by: https://github.com/helm/helm/issues/6374

**Comment by ferrarimarco** [comment] 2020-03-21 18:54
Can you try with the latest 2.x (`2.16.3`)?

**Comment by ferrarimarco** [comment] 2020-03-21 19:06
Confirmed. the 2.15.0 version has a fix for this, but can you try with the latest 2.x (2.16.3) directly? Thanks!

**Comment by zvfvrv** [comment] 2020-03-21 21:03
Hi @ferrarimarco , honestly i did nothing for helm installation, i took it as it is from the regular cluster build...so may i install a specific version from the Ansible script? or i must do it directly from the master instance?

**Closed** 2020-03-22 20:38 UTC
Labels: bug
